export type BaseLaborService = {
  name: string;
  description: string;
  keywords: string[];
  audience: "worker" | "employer";
};

export const BASE_LABOR_SERVICES: BaseLaborService[] = [
  { name: "전문 공인노무사 상담", description: "핵심 이슈의 사실관계와 절차 선택을 빠르게 정리해 초기 대응 전략을 설계합니다.", keywords: ["상담", "노무사", "진단", "전략"], audience: "worker" },
  { name: "임금체불 진정사건 대리", description: "미지급 임금·수당·퇴직금 증빙을 정리하고 노동청 진정 절차를 대리합니다.", keywords: ["임금", "체불", "미지급", "진정", "노동청", "퇴직금"], audience: "worker" },
  { name: "대지급금 신청 대리", description: "도산·폐업 또는 지급불능 정황을 검토해 대지급금 신청 절차를 대리합니다.", keywords: ["대지급금", "체당금", "도산", "폐업", "파산"], audience: "worker" },
  { name: "퇴직금 청구 대리", description: "퇴직금 산정 검토부터 청구 절차 진행까지 일괄 지원합니다.", keywords: ["퇴직금", "청구", "근속", "평균임금"], audience: "worker" },
  { name: "임금명세서 위반 대응", description: "임금명세서 미교부·허위교부 관련 사실관계 점검 및 대응을 지원합니다.", keywords: ["임금명세서", "미교부", "근로기준법"], audience: "worker" },
  { name: "최저임금 위반 대응", description: "최저임금 위반 여부 점검과 시정·청구 절차를 지원합니다.", keywords: ["최저임금", "시급", "위반"], audience: "worker" },
  { name: "연장·야간·휴일수당 청구", description: "근로시간 산정 및 가산수당 청구 절차를 지원합니다.", keywords: ["연장근로", "야간근로", "휴일근로", "수당"], audience: "worker" },
  { name: "연차휴가 미사용수당 청구", description: "연차 발생·소멸·수당 정산 검토와 청구를 지원합니다.", keywords: ["연차", "미사용수당", "휴가"], audience: "worker" },
  { name: "근로시간 위반 진단", description: "장시간 근로, 휴게시간 위반 등 근로시간 이슈를 진단합니다.", keywords: ["근로시간", "휴게시간", "주52시간"], audience: "worker" },
  { name: "포괄임금제 적법성 점검", description: "포괄임금 약정의 적법성과 임금 재산정 쟁점을 검토합니다.", keywords: ["포괄임금", "고정OT", "통상임금"], audience: "worker" },
  { name: "통상임금 재산정 자문", description: "통상임금 범위와 재산정 리스크를 분석하고 대응안을 제시합니다.", keywords: ["통상임금", "정기상여", "임금체계"], audience: "worker" },
  { name: "부당해고 구제신청 대리", description: "해고의 정당성·절차 적법성 검토 후 노동위원회 구제절차를 대리합니다.", keywords: ["부당해고", "해고", "구제신청", "노동위원회"], audience: "worker" },
  { name: "부당징계 구제신청 대리", description: "징계사유·양정·절차 위반 여부를 검토하고 구제절차를 대리합니다.", keywords: ["부당징계", "정직", "감봉", "징계"], audience: "worker" },
  { name: "부당전직·전보 대응", description: "전직·전보·인사발령의 정당성 검토 및 대응을 지원합니다.", keywords: ["전직", "전보", "인사발령", "부당전직"], audience: "worker" },
  { name: "권고사직·사직강요 대응", description: "권고사직 과정의 위법성 점검 및 증거정리를 지원합니다.", keywords: ["권고사직", "사직강요", "퇴사압박"], audience: "worker" },
  { name: "직장 내 괴롭힘 신고 대응", description: "괴롭힘 사건의 사실관계 정리, 신고·조사 대응을 지원합니다.", keywords: ["직장내괴롭힘", "괴롭힘", "폭언", "갑질"], audience: "worker" },
  { name: "직장 내 성희롱 대응", description: "성희롱 사건의 사내 절차 및 외부 대응을 지원합니다.", keywords: ["성희롱", "직장내성희롱", "성적언동"], audience: "worker" },
  { name: "산재보상 신청 대리", description: "업무상 재해 인정 및 급여 청구 절차를 대리합니다.", keywords: ["산재", "업무상재해", "요양급여"], audience: "worker" },
  { name: "업무상질병 산재 인정 대응", description: "질병의 업무관련성 입증 자료를 구성하고 산재 신청을 지원합니다.", keywords: ["업무상질병", "근골격계", "과로", "직업병"], audience: "worker" },
  { name: "장해급여 청구 지원", description: "치료 종료 후 장해등급 판단 및 장해급여 청구를 지원합니다.", keywords: ["장해급여", "장해등급", "산재"], audience: "worker" },
  { name: "유족급여·장의비 청구 지원", description: "산재 사망 사건의 유족급여 및 장의비 청구를 지원합니다.", keywords: ["유족급여", "장의비", "산재사망"], audience: "worker" },
  { name: "실업급여 이직확인서 대응", description: "이직사유 정정 및 이직확인서 관련 분쟁 대응을 지원합니다.", keywords: ["실업급여", "이직확인서", "구직급여"], audience: "worker" },
  { name: "부정수급 조사 대응", description: "고용보험 부정수급 조사·소명 절차 대응을 지원합니다.", keywords: ["부정수급", "고용보험", "소명"], audience: "worker" },

  { name: "사업주·인사담당 노무자문", description: "사업주/인사담당자의 인사노무 의사결정에 필요한 리스크 진단과 실행안을 제공합니다.", keywords: ["사업주", "인사팀", "hr", "노무자문"], audience: "employer" },
  { name: "취업규칙 제·개정 자문", description: "취업규칙 작성, 불이익변경 절차, 신고까지 지원합니다.", keywords: ["취업규칙", "불이익변경", "규정"], audience: "employer" },
  { name: "근로계약서 점검·작성", description: "근로계약서 적법성 점검 및 표준화 작성을 지원합니다.", keywords: ["근로계약서", "근로조건", "계약"], audience: "employer" },
  { name: "인사규정 정비 자문", description: "채용·평가·징계·퇴직 규정의 정합성과 리스크를 점검합니다.", keywords: ["인사규정", "징계규정", "취업규칙"], audience: "employer" },
  { name: "교대제·근무표 설계 자문", description: "교대제 패턴, 인력 운영, 수당 영향을 반영한 근무표를 설계합니다.", keywords: ["교대제", "근무표", "시프트", "스케줄", "교대근무"], audience: "employer" },
  { name: "임금체계 개편 자문", description: "직무·성과·연공 기반 임금체계 개편을 설계합니다.", keywords: ["임금체계", "연봉제", "직무급", "성과급"], audience: "employer" },
  { name: "성과급·인센티브 설계 자문", description: "성과보상 제도의 설계 및 법적 리스크를 점검합니다.", keywords: ["성과급", "인센티브", "보상"], audience: "employer" },
  { name: "인사평가 제도 설계", description: "평가체계 설계, 운영기준 수립, 분쟁예방 장치를 제공합니다.", keywords: ["인사평가", "평가제도", "성과관리"], audience: "employer" },
  { name: "징계위원회 운영 자문", description: "징계 절차의 공정성 확보와 문서화를 지원합니다.", keywords: ["징계위원회", "징계절차", "소명"], audience: "employer" },
  { name: "노동청 근로감독 대응", description: "근로감독 사전점검, 자료준비, 현장대응을 지원합니다.", keywords: ["근로감독", "노동청", "시정지시"], audience: "employer" },
  { name: "노동관계 법정의무 컴플라이언스 점검", description: "근로기준·산안·고용보험 등 법정 의무 준수 상태를 진단합니다.", keywords: ["컴플라이언스", "노동법", "법정의무"], audience: "employer" },
  { name: "4대보험 취득·상실 정정 자문", description: "4대보험 자격취득·상실·보수신고 오류 정정을 지원합니다.", keywords: ["4대보험", "취득", "상실", "보수"], audience: "employer" },
  { name: "노사협의회 설치·운영 자문", description: "노사협의회 설치, 의결·협의 안건 운영을 지원합니다.", keywords: ["노사협의회", "근로자참여", "협의"], audience: "employer" },
  { name: "고충처리제도 구축", description: "사내 고충처리 프로세스 설계와 운영을 지원합니다.", keywords: ["고충처리", "고충상담", "분쟁예방"], audience: "employer" },
  { name: "단체교섭 전략 자문", description: "단체교섭 준비, 의제설계, 교섭전략 수립을 지원합니다.", keywords: ["단체교섭", "노동조합", "교섭"], audience: "employer" },
  { name: "단체협약 검토 자문", description: "단체협약 조항의 적법성·실효성을 검토합니다.", keywords: ["단체협약", "노조", "협약검토"], audience: "employer" },
  { name: "노동쟁의 대응 자문", description: "쟁의행위 국면의 법적 리스크 및 대응전략을 지원합니다.", keywords: ["노동쟁의", "파업", "쟁의행위"], audience: "employer" },
  { name: "부당노동행위 구제신청 지원", description: "부당노동행위 해당성 검토 및 구제절차를 지원합니다.", keywords: ["부당노동행위", "노동위원회", "노조활동"], audience: "employer" },
  { name: "비정규직 차별시정 대응", description: "기간제·파견 근로자 차별 이슈의 시정 절차를 지원합니다.", keywords: ["비정규직", "차별시정", "기간제", "파견"], audience: "employer" },
  { name: "파견·도급 적법성 진단", description: "파견·도급 구조의 적법성 및 사용자책임 리스크를 진단합니다.", keywords: ["파견", "도급", "불법파견"], audience: "employer" },
  { name: "원·하청 노무리스크 점검", description: "원청·협력사 인력운영 구조의 노무 리스크를 점검합니다.", keywords: ["원하청", "협력사", "노무리스크"], audience: "employer" },
  { name: "직장폐쇄·쟁의 국면 대응", description: "노사갈등 심화 국면에서의 합법적 대응체계를 지원합니다.", keywords: ["직장폐쇄", "쟁의", "노사갈등"], audience: "employer" },
  { name: "기업 인사노무 실사(DD)", description: "M&A·투자 과정 인사노무 실사와 리스크 보고를 수행합니다.", keywords: ["실사", "DD", "M&A", "인수합병"], audience: "employer" },
  { name: "HR Due Diligence 보고서 작성", description: "채용·보상·노사관계 리스크를 구조화한 보고서를 제공합니다.", keywords: ["HRDD", "보고서", "리스크"], audience: "employer" },
  { name: "사내 교육(노동법·인사실무)", description: "관리자·실무자 대상 노동법 및 인사실무 교육을 제공합니다.", keywords: ["교육", "노동법교육", "인사실무"], audience: "employer" },
  { name: "직장 내 괴롭힘 예방체계 구축", description: "예방규정, 신고체계, 조사프로토콜을 통합 설계합니다.", keywords: ["괴롭힘예방", "신고체계", "조사프로토콜"], audience: "employer" },
  { name: "직장 내 성희롱 예방체계 구축", description: "성희롱 예방규정, 교육, 사건대응 체계를 구축합니다.", keywords: ["성희롱예방", "예방교육", "사건대응"], audience: "employer" },
  { name: "인사노무 정기 자문(월 고문)", description: "상시 자문 체계로 인사노무 이슈를 선제적으로 관리합니다.", keywords: ["정기자문", "월고문", "상시자문"], audience: "employer" },
  { name: "노무 진단 보고서 작성", description: "현장 인터뷰와 문서검토 기반의 종합 노무진단 보고서를 제공합니다.", keywords: ["노무진단", "진단보고서", "리스크진단"], audience: "employer" },
];
